FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    libzip-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install MySQL PDO extension
RUN docker-php-ext-install pdo_mysql zip

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

WORKDIR /var/www

# Copy application code
COPY . .

# Install PHP dependencies
ENV APP_ENV=prod
RUN composer install --no-dev --optimize-autoloader

# Fix permissions for www-data
RUN chown -R www-data:www-data /var/www

EXPOSE 9000

COPY docker/entrypoint.prod.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
CMD ["php-fpm"]